package configuration

const (
	WEB_SERVICE = "https://www.tibiakray.info/"
)

const (
	//lenguaje
	LENGUAJE_RETURN = iota + 1
	LENGUAJE_NEXT
	LENGUAJE_UPDATE
	LENGUAJE_NOT_HAVE_ITEM
	LENGUAJE_DELETE_ITEM
	LENGUAJE_HISTORY_ITEM
	LENGUAJE_COPY
	LENGUAJE_COPY_TEXT
	LENGUAJE_CREATE_CHARACTER
	LENGUAJE_CHARACTER_NOT_NULL
	LENGUAJE_CHARACTER
	LENGUAJE_MY_VALUE
	LENGUAJE_ORIGIN_VALUE
	LENGUAJE_EDIT
	LENGUAJE_NAME_ITEM
)
